import { PrismaClient } from "@prisma/client";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const { movie: Movie } = new PrismaClient();

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={styles.movielist}>
          {data.map((item) => (
            <li key={item.id}>
              <span>
                <strong>{item.title}</strong>
              </span>
              <span>{item.year}</span>
              <span>{item.description}</span>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const movies = await Movie.findMany();

  return {
    props: {
      data: movies,
    },
  };
};
